### ISSUE TITLE
Is this a lab or a readme?

### ISSUE THREAD

**Issue by aenbar** [learn-co-curriculum/opening-a-lab-osx#1]
I was following the instructions to do this since the language says things like `To get started, in Learn click "View on GitHub".` and `To clone, make sure you've first clicked on the SSH link, then click the
copy button next to the Clone URL to copy it to your clipboard.` but then later it says `When you type learn open in your terminal, you'll see:` and the image shows the fork and pull request lights but i don't have those lights. So feels like i'm missing something.

**Comment by AnnJohn** [comment]
@aviflombaum  ^^

**Comment by matbalez-zz** [comment]
Another new user found this confusing today too. This is a readme and she was trying to follow and perform the instruction. 

The text needs to make it clear that the instructions are not to be followed, but what you _would_ do if you were using the Github work flow.

**Comment by aviflombaum** [comment]
Thoughts everyone on a74ea71 clearing this up?

**Comment by matbalez-zz** [comment]
I think the changes make it much clearer.
